services:
  notebooks:
    build: .
    container_name: notebooks-container
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebooks
        target: /notebooks
    env_file: .env
